version: '3.8'
services:
  stats-server:
    build: ./stats/stats-server
    image: stats-server-image
    container_name: ewm-stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:15.1-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    volumes:
      - /ewm-stats-db
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-main-service:
      build: ./main
      image: ewm-main-service-image
      container_name: ewm-main-service
      depends_on:
        - ewm-db
      ports:
        - "8080:8080"
      environment:
        - STATS_SERVER_URL=http://ewm-stats-server:9090
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=root

  ewm-db:
    image: postgres:15.1-alpine
    container_name: ewm-db
    ports:
      - "6547:5432"
    volumes:
      - /ewm-db
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root