version: '3.8'
services:
  stats-server:
    build: ./stats/stats-server
    image: stats-server-image
    container_name: ewm-stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432

  stats-db:
    image: postgres:15.1-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    volumes:
      - /ewm-stats-db
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-main-service:
      ports:
        - "8080:8080"
      environment:
        - CLIENT_URL=http://stats-server:9090
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
        - SPRING_DATASOURCE_USERNAME=
        - SPRING_DATASOURCE_PASSWORD=
